name: Checkout

on: [push]

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install Cypress
        run: npm install
      - name: Cypress run
        id: cypress
        uses: cypress-io/github-action@v4
        with:
          browser: chrome
